### ISSUE TITLE
Failed to load remote context

### ISSUE THREAD

**Issue by jakubklimek** [dotnetrdf/dotnetrdf#376]
When trying to convert a JSON-LD 1.1 file with remote context, I get:
```cmd
> rdfConvert.exe 2.jsonld -out:2.ttl
rdfConvert: Converting Input File '2.jsonld' to '2.ttl'...
rdfConvert: Error: Error Converting Input File '2.jsonld' due to a Unexpected Exception
Failed to load remote context from https://ofn.gov.cz/turistické-cíle/2020-07-01/kontexty/turistický-cíl.jsonld.
```
The file is at: https://ofn.gov.cz/turistické-cíle/2020-07-01/příklady/2.jsonld and works OK in [JSON-LD Playground](https://json-ld.org/playground/)

**Comment by kal** [comment]
Hi @jakubklimek 

Thanks for the report. The immediate issue is that rdfconvert is still a .NET 4 Framework application and doesn't support TLS 1.2. I've changed that in the local build and confirmed that it can now load the main context file, but I still run into some problems with the nested contexts that are referenced within that. I'll have to run a few more tests, but it does look like we will need an updated release of the toolkit (we need to do that in any case as there have been a few performance and bug fixes since the last time the toolkit was updated)

**Comment by kal** [comment]
I fixed a couple of issues that were causing this JSON-LD file to fail to convert. The fixes will go into the 2.7.0 release and we will release a new version of the command line tools along with that release.

**Comment by LuzLoz** [comment]
Hi guys i'm using release 2.7.0 now and i'm still facing this issue i have:
`            //string contextUri = "http://localhost/context/adapt/WD/2021/03/context.jsonld";
            string contextUri = "http://purl.thermofisher.com/context/adapt/WD/2021/03/context.jsonld";
            JsonLdProcessorOptions options = new JsonLdProcessorOptions();
            RemoteContextProvider remoteContext = new RemoteContextProvider(options);


            JsonLdRemoteContext jsonldContext = remoteContext.GetRemoteContext(new Uri(contextUri));`
and i'm getting the error `            JsonLdRemoteContext jsonldContext = remoteContext.GetRemoteContext(new Uri(contextUri));
`

**Comment by kal** [comment]
Hi @LuzLoz 

Can you let us know what the inner exception is on the exception that is raised. That will help to narrow down what the cause of the failure to load the remote context is. 

Cheers

Kal

**Comment by LuzLoz** [comment]
Hi Kal,

Actually there is no inner exception, but i try to understand what is happening following the [RemoteContextProvider](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/JsonLd/RemoteContextProvider.cs) inside its method _GetRemotecontext_, and I see there is a method _LoadFunction_ which asks if options.DocumentLoader is set otherwise it uses **_DefaultDocumentLoader.LoadJson_** (this is my case because i'm not setting up a DocumentLoader in the JsonLdProcessorOptions _options_) there I can see is throwing an Exception with stackTrace:
```   at VDS.RDF.JsonLd.DefaultDocumentLoader.<ParseLinkHeaders>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at VDS.RDF.JsonLd.DefaultDocumentLoader.LoadJson(Uri remoteRef, JsonLdLoaderOptions loaderOptions)
   at client_library_tests.JsonLdTests.LoadJson(Uri remoteRef, JsonLdLoaderOptions loaderOptions, JsonLdProcessorOptions options) in /Users/luz.lozano/Desktop/Luna/git/adapt-library/client-library-tests/JsonLdTests.cs:line 188
```
and message: _"Object reference not set to an instance of an object."_

and then just the 
`VDS.RDF.JsonLd.JsonLdProcessorException has been thrown Failed to load remote context from http://purl.thermofisher.com/context/adapt/WD/2021/03/context.jsonld."
`

Then inside the [DefaultDocumentLoader](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/JsonLd/DefaultDocumentLoader.cs) method _LoadJson_ I don't quite get what is happening

I hope this helps a bit
thanks

**Comment by kal** [comment]
Hi @LuzLoz ,

From a quick eyeball of the code, it looks like the failure might be occurring in trying to process Link headers in the HTTP response headers - that's the only place I can see where there is a Where().Select().ToList() which would match the stack trace given. The only problem is that I can't see an obvious location in the code where that would throw the exception you are seeing.

However, what this says to me is that dotNetRDF isn't having a problem with the context itself, but with the HTTP response that is coming back from the server. That might be because there's a bug in the handling in dotNetRDF, or it might be that there's something wrong in the response payload (and that means that dotNetRDF needs to report a more useful error!). I'm not totally sure what the best way to help debug this is. I think that there are two possible options:

1) If you have the time you could try building dotNetRDF yourself and linking in the project instead of the nuget package so that you can step through the code. I realise that's quite a lot of effort though!
2) Alternatively if you have a tool like Postman or perhaps even just the developer tools in Chrome/Firefox can you get a copy / screenshot of the HTTP headers that are coming back in the response from your test server? That might help to figure out what's going on (or at least rule out the possibility of problems in parsing the response headers)

**Comment by LuzLoz** [comment]
Hi @kal ,
This first image is from _purl.thermo.com_ url 
<img width="281" alt="Screen Shot 2021-04-14 at 2 25 02 PM" src="https://user-images.githubusercontent.com/2007222/114781345-647dfe80-9d2d-11eb-94fa-3a9053154252.png">
This second one is from the _localhost_,
<img width="333" alt="Screen Shot 2021-04-14 at 2 25 26 PM" src="https://user-images.githubusercontent.com/2007222/114781354-6942b280-9d2d-11eb-9d59-13de6854ace6.png">

i'm gonna try providing my own JsonLdProcessorOptions.DocumentLoader to see if i can make it work, but still it would be nice to have it working with the DefaultDocumentLoader.

thanks a lot

**Comment by LuzLoz** [comment]
I confirm that using my own DocumentLoader i could get the context:
```
public Main(){
            string contextUri = "http://purl.thermofisher.com/context/adapt/WD/2021/03/context.jsonld";
            JsonLdProcessorOptions options = new JsonLdProcessorOptions();
            Func<Uri, JsonLdLoaderOptions, RemoteDocument> myDocumentLoader = LocalLoad;
            options.DocumentLoader = myDocumentLoader;
            RemoteContextProvider remoteContext = new RemoteContextProvider(options);
            JsonLdRemoteContext jsonldContext = remoteContext.GetRemoteContext(new Uri(contextUri));
}
private static RemoteDocument LocalLoad(Uri url, JsonLdLoaderOptions options)
        {
            //var responseString = GetRemoteContext(url.ToString());
            var request = (HttpWebRequest)WebRequest.Create(url);
            request.Method = "GET";
            request.ContentType = "application/json";
            request.Accept = "application/json";
            string responseBody = "";
            try
            {
                using (WebResponse response = request.GetResponse())
                {
                    using (Stream strReader = response.GetResponseStream())
                    {
                        if (strReader == null)
                            throw new Exception("No Response when trying to retrieve remote context");
                        using (StreamReader objReader = new StreamReader(strReader))
                        {
                            responseBody = objReader.ReadToEnd();
                        }
                    }
                }
            }
            catch (WebException ex)
            {
                Console.WriteLine(ex.Message);
            }
            var ret = new RemoteDocument
            {
                ContextUrl = new Uri("http://www.w3.org/ns/json-ld#context"),
                DocumentUrl = url,
                Document = JToken.Parse(responseBody),
            };
            return ret;
        }
```
