### ISSUE TITLE
TriGParser in 2.7.5 does not accept . in prefixed IRIs

### ISSUE THREAD

**Issue by daghovland** [dotnetrdf/dotnetrdf#542]
The TriGParser does not accept . in prefied IRIs, f.ex. `exdata:test.1` 

Reproduce:
Running this code with dotnetrdf 2.7.5
```
 var trigParser = new TriGParser();
var tStore = new TripleStore();
trigParser.Load(tStore, new StringReader("@prefix exdata: <https://example.com/data/>. exdata:test1 { exdata:test.1 a <http://example.com/Thing> .}"));
```
leads to this error
```
[xUnit.net 00:00:03.43]       VDS.RDF.Parsing.RdfParseException : [PlainLiteralToken at Line 1 Column 72 to Line 1 Column 74] Unexpected Token 'VDS.RDF.Parsing.Tokens.PlainLiteralToken' encountered, expected a URI/QName as the Predicate of a Triple
[xUnit.net 00:00:03.43]       Stack Trace:
[xUnit.net 00:00:03.43]            at VDS.RDF.Parsing.TriGParser.TryParsePredicateObjectList(TriGParserContext context, Uri graphUri, INode subj)
[xUnit.net 00:00:03.43]            at VDS.RDF.Parsing.TriGParser.TryParseTriples(TriGParserContext context, Uri graphUri)
[xUnit.net 00:00:03.43]            at VDS.RDF.Parsing.TriGParser.TryParseGraph(TriGParserContext context)
[xUnit.net 00:00:03.43]            at VDS.RDF.Parsing.TriGParser.Parse(TriGParserContext context)
[xUnit.net 00:00:03.43]            at VDS.RDF.Parsing.TriGParser.Load(IRdfHandler handler, TextReader input)
[xUnit.net 00:00:03.43]            at VDS.RDF.Parsing.TriGParser.Load(ITripleStore store, TextReader input)
```

Replacing `exdata:test.1` with either `exdata:test1` or `<https://example.com/data/test.1>` does not give an error and parses successfully. 

The W3C TriG spec seems quite clear that . is allowed inside a prefixed IRI (just not at the start or end)

**Comment by kal** [comment]
This is fixed in 3.0

**Comment by daghovland** [comment]
This bug is still present. The test still fails on release 3.1.1
